//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBookie.i18n {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBookie.i18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über eBookie ähnelt.
        /// </summary>
        public static string AboutPage_title {
            get {
                return ResourceManager.GetString("AboutPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die eBookie ähnelt.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählten Ordner zur Liste hinzufügen ähnelt.
        /// </summary>
        public static string btn_addFolder_tooltip {
            get {
                return ResourceManager.GetString("btn_addFolder_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück zur vorherigen Oberfläche ähnelt.
        /// </summary>
        public static string btn_Back_tooltip {
            get {
                return ResourceManager.GetString("btn_Back_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner, der E-Books enthält auswählen ähnelt.
        /// </summary>
        public static string btn_chooseFolder_tooltip {
            get {
                return ResourceManager.GetString("btn_chooseFolder_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm beenden ähnelt.
        /// </summary>
        public static string btn_Exit_tooltip {
            get {
                return ResourceManager.GetString("btn_Exit_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zur Hauptoberfläche ähnelt.
        /// </summary>
        public static string btn_Home_tooltip {
            get {
                return ResourceManager.GetString("btn_Home_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner aus der Liste entfernen ähnelt.
        /// </summary>
        public static string btn_removeEBookFolder_tooltip {
            get {
                return ResourceManager.GetString("btn_removeEBookFolder_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingaben zurücksetzen ähnelt.
        /// </summary>
        public static string btn_Reset_tooltip {
            get {
                return ResourceManager.GetString("btn_Reset_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change the language to english. ähnelt.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string exitApp {
            get {
                return ResourceManager.GetString("exitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner auswählen: ähnelt.
        /// </summary>
        public static string lbl_chooseFolder {
            get {
                return ResourceManager.GetString("lbl_chooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungsdatum: ähnelt.
        /// </summary>
        public static string lbl_lastModified {
            get {
                return ResourceManager.GetString("lbl_lastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzter Änderer: ähnelt.
        /// </summary>
        public static string lbl_lastModifier {
            get {
                return ResourceManager.GetString("lbl_lastModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenzbestimmungen: ähnelt.
        /// </summary>
        public static string lbl_license {
            get {
                return ResourceManager.GetString("lbl_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        public static string lbl_version {
            get {
                return ResourceManager.GetString("lbl_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hiermit wird unentgeltlich jeder Person, die eine Kopie der Software und der zugehörigen Dokumentationen (die &quot;Software&quot;) erhält, die Erlaubnis erteilt, sie uneingeschränkt zu benutzen, inklusive und ohne Ausnahme dem Recht, sie zu verwenden, kopieren, ändern, fusionieren, verlegen, verbreiten, unterlizenzieren und/oder zu verkaufen, und Personen, die diese Software erhalten, diese Rechte zu geben, unter den folgenden Bedingungen: ähnelt.
        /// </summary>
        public static string license_term_1 {
            get {
                return ResourceManager.GetString("license_term_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der obige Urheberrechtsvermerk und dieser Erlaubnisvermerk sind in allen Kopien oder Teilkopien der Software beizulegen. ähnelt.
        /// </summary>
        public static string license_term_2 {
            get {
                return ResourceManager.GetString("license_term_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DIE SOFTWARE WIRD OHNE JEDE AUSDRÜCKLICHE ODER IMPLIZIERTE GARANTIE BEREITGESTELLT, EINSCHLIESSLICH DER GARANTIE ZUR BENUTZUNG FÜR DEN VORGESEHENEN ODER EINEM BESTIMMTEN ZWECK SOWIE JEGLICHER RECHTSVERLETZUNG, JEDOCH NICHT DARAUF BESCHRÄNKT. IN KEINEM FALL SIND DIE AUTOREN ODER COPYRIGHTINHABER FÜR JEGLICHEN SCHADEN ODER SONSTIGE ANSPRÜCHE HAFTBAR ZU MACHEN, OB INFOLGE DER ERFÜLLUNG EINES VERTRAGES, EINES DELIKTES ODER ANDERS IM ZUSAMMENHANG MIT DER SOFTWARE ODER SONSTIGER VERWENDUNG DER SOFTWARE ENTSTANDEN [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string license_term_3 {
            get {
                return ResourceManager.GetString("license_term_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die MIT-Lizenz ähnelt.
        /// </summary>
        public static string LicenseTermsPage_h1 {
            get {
                return ResourceManager.GetString("LicenseTermsPage_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenzbestimmungen ähnelt.
        /// </summary>
        public static string LicenseTermsPage_title {
            get {
                return ResourceManager.GetString("LicenseTermsPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenzbestimmungen ähnelt.
        /// </summary>
        public static string LicenseTermsPage_title1 {
            get {
                return ResourceManager.GetString("LicenseTermsPage_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autor ähnelt.
        /// </summary>
        public static string lvc_author {
            get {
                return ResourceManager.GetString("lvc_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buch unwiderruflich löschen ähnelt.
        /// </summary>
        public static string lvc_btnDeleteBook_tooltip {
            get {
                return ResourceManager.GetString("lvc_btnDeleteBook_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buch nicht mehr anzeigen ähnelt.
        /// </summary>
        public static string lvc_btnHideBook_tooltip {
            get {
                return ResourceManager.GetString("lvc_btnHideBook_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ö ähnelt.
        /// </summary>
        public static string lvc_btnOpenEBookFolderPath {
            get {
                return ResourceManager.GetString("lvc_btnOpenEBookFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordnerpfad im Explorer öffnen ähnelt.
        /// </summary>
        public static string lvc_btnOpenEBookFolderPath_tooltip {
            get {
                return ResourceManager.GetString("lvc_btnOpenEBookFolderPath_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateipfad aufrufen ähnelt.
        /// </summary>
        public static string lvc_btnOpenPath_tooltip {
            get {
                return ResourceManager.GetString("lvc_btnOpenPath_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die L ähnelt.
        /// </summary>
        public static string lvc_deleteBook {
            get {
                return ResourceManager.GetString("lvc_deleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buch unwiderruflich löschen ähnelt.
        /// </summary>
        public static string lvc_deleteBook_tooltip {
            get {
                return ResourceManager.GetString("lvc_deleteBook_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gerät zur Synchronisierung ähnelt.
        /// </summary>
        public static string lvc_device {
            get {
                return ResourceManager.GetString("lvc_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ö ähnelt.
        /// </summary>
        public static string lvc_openPath {
            get {
                return ResourceManager.GetString("lvc_openPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateipfad im Explorer öffnen ähnelt.
        /// </summary>
        public static string lvc_openPath_tooltip {
            get {
                return ResourceManager.GetString("lvc_openPath_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad zum Ordner ähnelt.
        /// </summary>
        public static string lvc_path {
            get {
                return ResourceManager.GetString("lvc_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die L ähnelt.
        /// </summary>
        public static string lvc_removeEBookFolder {
            get {
                return ResourceManager.GetString("lvc_removeEBookFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner nicht mehr synchronisieren ähnelt.
        /// </summary>
        public static string lvc_removeEBookFolder_tooltip {
            get {
                return ResourceManager.GetString("lvc_removeEBookFolder_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gerät zur Synchronisierung ähnelt.
        /// </summary>
        public static string lvc_syncDevice {
            get {
                return ResourceManager.GetString("lvc_syncDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gerät mit dem die Synchronisierung stattfindet. ähnelt.
        /// </summary>
        public static string lvc_syncDevice_tooltip {
            get {
                return ResourceManager.GetString("lvc_syncDevice_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        public static string lvc_title {
            get {
                return ResourceManager.GetString("lvc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ausgewählte Sprache wurde geladen und wird nach einem Neustart der Anwendung aktiv. ähnelt.
        /// </summary>
        public static string mbx_q_restart_app_1 {
            get {
                return ResourceManager.GetString("mbx_q_restart_app_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die Anwendung jetzt neustarten? ähnelt.
        /// </summary>
        public static string mbx_q_restart_app_2 {
            get {
                return ResourceManager.GetString("mbx_q_restart_app_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über eBookie ähnelt.
        /// </summary>
        public static string menuItem_About {
            get {
                return ResourceManager.GetString("menuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        public static string menuItem_Extras {
            get {
                return ResourceManager.GetString("menuItem_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback senden ähnelt.
        /// </summary>
        public static string menuItem_Feedback {
            get {
                return ResourceManager.GetString("menuItem_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string menuItem_Help {
            get {
                return ResourceManager.GetString("menuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bücher importieren ähnelt.
        /// </summary>
        public static string menuItem_importBooks {
            get {
                return ResourceManager.GetString("menuItem_importBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm ähnelt.
        /// </summary>
        public static string menuItem_Program {
            get {
                return ResourceManager.GetString("menuItem_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Programm wird unter den Bestimmungen der ähnelt.
        /// </summary>
        public static string tb_footnote_2 {
            get {
                return ResourceManager.GetString("tb_footnote_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Massachusetts Institute of Technology (MIT)-Lizenz ähnelt.
        /// </summary>
        public static string tb_footnote_3 {
            get {
                return ResourceManager.GetString("tb_footnote_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die von 1988 vertrieben. ähnelt.
        /// </summary>
        public static string tb_footnote_4 {
            get {
                return ResourceManager.GetString("tb_footnote_4", resourceCulture);
            }
        }
    }
}
